server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api/patients/ {
        proxy_pass http://192.168.49.2:30277/;
    }

    location /api/doctors/ {
        proxy_pass http://192.168.49.2:32548/;
    }

    location /api/appointments/ {
        proxy_pass http://192.168.49.2:30632/;
    }
}
